name: build-base
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Handle .dockerignore
      run: cd server-ce && cp .dockerignore ../
    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
          context: server-ce/..
          push: true
          tags: shell20021020/sharelatex-base:latest
          cache-from: type=registry,ref=shell20021020/sharelatex-base:cache
          cache-to: type=registry,ref=shell20021020/sharelatex-base:cache,mode=max
          file: server-ce/Dockerfile-base
